<?php

/*
 * This file is part of the zimbrucode package.
 *
 * (c) Junjulini
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

/**
 * @var bool $logged
 */

?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="robots" content="noindex, nofollow">
        <title>Server Error</title>

        <style>
            #debugger-error { all: initial; position: absolute; top: 0; left: 0; right: 0; height: 70vh; min-height: 400px; display: flex; align-items: center; justify-content: center; z-index: 1000 }
            #debugger-error div { all: initial; max-width: 550px; background: white; color: #333; display: block }
            #debugger-error h1 { all: initial; font: bold 50px/1.1 sans-serif; display: block; margin: 40px }
            #debugger-error p { all: initial; font: 20px/1.4 sans-serif; margin: 40px; display: block }
            #debugger-error small { color: gray }
            #debugger-error small span { color: silver }
        </style>
    </head>
    <body>
        <div id=debugger-error>
            <div>
                <h1>Server Error</h1>

                <p>We're sorry! The server encountered an internal error and
                was unable to complete your request. Please try again later.</p>

                <p><small>Error 500<span> | <?php echo wp_date('j.n.Y H:i') ?></span><?php if (!$logged): ?><br>Debugger is unable to log error.<?php endif ?></small></p>
            </div>
        </div>
    </body>
</html>